### PR TITLE
added vars for jenkins pub/private keys

### PR DESCRIPTION
**Pull request by cfoskin**
JIRA: https://issues.jboss.org/browse/AGDIGGER-230

Changes: updated jenkins cli calls to use pub/private keys and allow this to be overridden by the user.

Verification steps in JIRA

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@cfoskin i've reviewed the code and the changes look good. Are there some verification steps here?

**Comment by aliok** [comment]
I am verifying this now...

**Comment by aliok** [comment]
@cfoskin there is an example here showing how to use user's home: https://github.com/cfoskin/aerogear-digger-installer/blob/da23a088a61745661a6d7901222e595b700abb2a/provision-osx/tasks/download_certs.yml#L7

**Comment by cfoskin** [comment]
@aliok  Maybe I do not understand how digger installer works fully, but where does ```-e jenkins_private_key_password``` come from? Where is this specified and how does it work?

**Comment by cfoskin** [comment]
@aliok  I will update the way I am using users home also

**Comment by aliok** [comment]
@cfoskin "jenkins_private_key_password" is added part of https://issues.jboss.org/browse/AGDIGGER-229

It allows us to feed the password for the private key.

**Comment by aliok** [comment]
👁

**Pull request merged**
